/// @file       io_hdf5.cpp 
/// @brief      Contains functions to read data from HDF5 files
///              
/// @author     Shivan Khullar
/// @date       June 2024



#include <hdf5.h>
#include "../../../include/linker/io.h"



/// @brief                      Function to get the last group 
///                             (traverse down the hdf5 file structure to the dataset)
/// @param subgroup_struct      The subgroup instance of a group struct 
/// @param group                Name of the group or subgroup
/// @return                     
hid_t get_last_group(Group_struct *subgroup_struct, hid_t group)
{
        if (subgroup_struct->subgroup!=NULL)
        {
                //std::cout << "Trying for group: " << subgroup_struct->name << std::endl;
                hid_t grp = H5Gopen(group, &subgroup_struct->name[0], H5P_DEFAULT);
                //group.openGroup(subgroup_struct->name);
                hid_t grp1 = get_last_group(subgroup_struct->subgroup, grp);
                //H5::Group grp1 = get_last_group(subgroup_struct->subgroup, grp);
                //std::cout << "Hi, opened group: " << subgroup_struct->name << std::endl;
                return grp1;
                //gname = file_arch->subgroup->name;
        }
	else
	{
                //std::cout << "Reached bottom group, this is a dataset: " << subgroup_struct->name << std::endl;
                //H5::Group grp = group.openGroup(subgroup_struct->name);
                //std::cout << "Hi, opened last group: " << subgroup_struct->name << std::endl;
                return group;
        }
}



/// @brief                      Function to read double data from an hdf5 file
/// @param params               The parameters struct
/// @param snap_num             The snapshot number
/// @param field_to_read        The field to read from the dataset
/// @param cloud_name           The name of the cloud
/// @return                     The data read from the dataset
std::vector<double> read_cloud_data_double(Params &params, int snap_num, std::string field_to_read, std::string cloud_name)
{
        // Handle the file and groups
        Group_struct *file_arch = create_group(params.file_arch_root);
        file_arch->subgroup = create_group(cloud_name);
        file_arch->subgroup->subgroup = create_group(params.file_arch_cloud_subgroup);
        file_arch->subgroup->subgroup->subgroup = create_group(field_to_read);
        std::string fname = params.path+params.filename_base_prefix+get_snapshot_name(snap_num)+params.filename_base_suffix;
	
        // Open the file and go to the last group with dataset
	hid_t file = H5Fopen (&fname[0], H5F_ACC_RDONLY, H5P_DEFAULT);
        std::string root = file_arch->name;
        hid_t grp_root = H5Gopen(file, &root[0], H5P_DEFAULT);
        hid_t last_group = get_last_group(file_arch->subgroup, grp_root);
        hid_t dataset = H5Dopen(last_group, &field_to_read[0], H5P_DEFAULT);

        // Read the data from the dataset        
        hid_t dataspace = H5Dget_space (dataset);
        int rank = H5Sget_simple_extent_ndims (dataspace);
        hsize_t dims_out[1];
        int status_n  = H5Sget_simple_extent_dims (dataspace, dims_out, NULL);
        std::vector<double> data(dims_out[0]);
        hid_t memspace = H5Screate_simple (rank, dims_out, NULL);
        //DataSpace memspace(rank, dims_out);
        herr_t status = H5Dread (dataset, H5T_IEEE_F64LE, memspace, dataspace,
                      H5P_DEFAULT, &data[0]);

        delete file_arch;
        return data;
}



/// @brief                      Function to read the mass of a cloud from 
///                             the hdf5 file generated by the matcher program
/// @param params               The parameters struct
/// @param snap_num             The snapshot number
/// @param cloud_name           The name of the cloud
/// @return                     The mass of the cloud
double read_mass(Params &params, int snap_num, std::string cloud_name)
{
        // Handle the file and groups
        std::string fname = params.path+params.write_filename_base_prefix + get_snapshot_name(snap_num) + "_" + get_snapshot_name(snap_num+1)
                                + params.write_filename_base_suffix;
        hid_t file = H5Fopen (&fname[0], H5F_ACC_RDONLY, H5P_DEFAULT);
        std::string root = "/";
        hid_t grp_root = H5Gopen(file, &root[0], H5P_DEFAULT);
        hid_t parent_group = H5Gopen(grp_root, "parent_group", H5P_DEFAULT);
        //std::string cloud_name = get_cloud_name(cloud_num, params);
        hid_t cloud_data_group = H5Gopen(parent_group, &cloud_name[0], H5P_DEFAULT);

        // Read the mass of the cloud from the dataset
	std::string dset_name = "total_mass_parent";
        hid_t dataset = H5Dopen(cloud_data_group, &dset_name[0], H5P_DEFAULT);
        hid_t dataspace = H5Dget_space (dataset);
        int rank = H5Sget_simple_extent_ndims (dataspace);
        hsize_t dims_out[1];
        int status_n  = H5Sget_simple_extent_dims (dataspace, dims_out, NULL);
        hid_t memspace = H5Screate_simple (rank, dims_out, NULL);
        double total_mass;
        herr_t status = H5Dread (dataset, H5T_IEEE_F64LE, memspace, dataspace,
                      H5P_DEFAULT, &total_mass);

        return total_mass;
}



/// @brief              Function to get the information of a child
///                     (used in get_child_list to get the names of 
///                     and mass donated/obtained fractions of the 
///                     children
/// @param loc_id       The location id
/// @param name         The name of the child
/// @param linfo        The link info
/// @param opdata       The operation data
/// @return             The error code
herr_t child_info(hid_t loc_id, const char *name, const H5L_info_t *linfo, void *opdata)
{
        hid_t group;
        auto group_names=reinterpret_cast< std::vector<std::string>* >(opdata);
        group = H5Gopen2(loc_id, name, H5P_DEFAULT);

        group_names->push_back(name);
        //std::cout << "Name : " << name << std::endl;
        H5Gclose(group);
        return 0;
}



/// @brief                      Function to get the list of children of a cloud
/// @param params               The parameters struct
/// @param snap_num             The snapshot number
/// @param cloud_name           The name of the cloud
/// @param child_list_names     The list of names of the children
/// @param child_list_fracs     The list of mass fractions donated by the 
///                             parent, to the children
void get_child_list(Params &params, int snap_num, std::string cloud_name, std::vector<std::string> &child_list_names, std::vector<double> &child_list_fracs)
{
        // Handle the file and groups
        std::string fname = params.path+params.write_filename_base_prefix + get_snapshot_name(snap_num) + "_" + get_snapshot_name(snap_num+1)
                                + params.write_filename_base_suffix;
        hid_t file = H5Fopen (&fname[0], H5F_ACC_RDONLY, H5P_DEFAULT);
        std::string root = "/";
        hid_t grp_root = H5Gopen(file, &root[0], H5P_DEFAULT);
        hid_t parent_group = H5Gopen(grp_root, "parent_group", H5P_DEFAULT);
        //std::string cloud_name = get_cloud_name(cloud_num, params);
        hid_t cloud_data_group = H5Gopen(parent_group, &cloud_name[0], H5P_DEFAULT);
        hid_t children = H5Gopen(cloud_data_group, "children", H5P_DEFAULT);

        // Get the names of the children and the mass fractions donated to them
        std::vector<std::string> child_names;
	herr_t idx = H5Literate(children, H5_INDEX_NAME, H5_ITER_INC, NULL, child_info, &child_names);
        std::cout << "There are " << child_names.size() << " children for this cloud" << std::endl;
        // Iterate over children
        for (int i=0; i<child_names.size(); i++)
        {
                child_list_names.push_back(child_names[i]); 
                std::string child_name = child_names[i]; 
                hid_t child = H5Gopen(children, &child_name[0], H5P_DEFAULT);

                // Read the mass fraction donated to the child
                hid_t dataset = H5Dopen(child, "parents_mass_frac_to_child", H5P_DEFAULT);
                hid_t dataspace = H5Dget_space (dataset);
                int rank = H5Sget_simple_extent_ndims (dataspace);
                hsize_t dims_out[1];
                int status_n  = H5Sget_simple_extent_dims (dataspace, dims_out, NULL);
                hid_t memspace = H5Screate_simple (rank, dims_out, NULL);
                double frac;
                herr_t status = H5Dread (dataset, H5T_IEEE_F64LE, memspace, dataspace,
                      H5P_DEFAULT, &frac);
                child_list_fracs.push_back(frac);
                std::cout << "Child " << i << " is " << child_names[i] <<" or "<< child_list_names[i] << ", frac: " << frac << std::endl;
                //std::cout << "Total mass for this cloud is: " << total_mass << std::endl;
        }
}
