# Select Target Computer
#
# Please uncomment your system. 
# Don't commit changes to this file unless you add support for
# a new system.
#
#############

#SYSTYPE="Mac"
#SYSTYPE="Niagara"
SYSTYPE="CITA"
